class Questionario {
    constructor(pergunta, respontaCerta, resposta2 , resposta3, resposta4) {
        this.pergunta = pergunta;
        this.respontaCerta = respontaCerta;
        this.resposta2 = resposta2;
        this.resposta3 = resposta3;
        this.resposta4 = resposta4;
    }
}

// Criação da lista de perguntas
//const pg = new Questionario("", "", "", "", "");
const teste = new Questionario("Qual é o nome do seu melhor amigo?", "José", "João", "Pedro", "Paulo");
const pg1 = new Questionario("O que é CESTA DE BENS?", "é o conjunto de uma quantidade de determinado bens e serviço", "é uma diferença entre bens e serviço", "Refere-se a satisfação completa do cliente", "Consiste na necessidade de um bem ou serviço");
const pg2 = new Questionario("A microeconomia tem o foco:", "Nos consumidores", "Nas empresas", "No governo", "No mercado");
const pg3 = new Questionario("O que significa Utilidade Total", "Refere-se a satisfação completa pelo consumo de todas as quantidades", "Refere-se a satisfação incompleta pelo consumo de todas as quantidades", "Refere-se a satisfação completa pelo consumo de todas as ideias", "Refere-se o questionamento completa pelo consumo de todas as quantidades");
const pg4 = new Questionario("O que significa Utilidade Marginal", "Consumo a mais de um determinado bem ou serviço", "Consumo de um determinado bem ou serviço", "Consumo de conteudos economicos", "serviço relacionados a marginal do negocio");
const pg5 = new Questionario("O que significa processo?", "processo é uma ordenação específica das atividades de trabalho no tempo e no espaço com um começo, um fim e entradas e saídas claramente identificadas", "processo é uma ordenação específica das atividade remuneradas com o foco em organizar um setor especifico", "processo é um setor de estudo voltado a organizar situaçoes onde é preciso ter uma organização maior e diciplina", "processo é um assunto da diciplina de direito: organização de um setor especifico");
const pg6 = new Questionario("O processo de agregar pessoas é definido com:", "é a porta de entrada das pessoas na organização, constituído basicamente pelo recrutamento e seleção de pessoas", "é o momento da empresa onde procuram parceiro fora da empresa para pedir ajuda de negocio", "é uma situação comum em pequenas empresas onde o lider procura incentivo fiscal do governo ou organizações maiores", "é a situação onde o lider procura ajuda de negocio para a empresa ou para o setor comum");
const pg7 = new Questionario("O processo de aplicar pessoas é definido com:", "consiste na integração, orientação para que o novo colaborador conheça a empresa e o que se espera dele, o cargo que vai ocupar e o acompanhamento do seu desempenho, incluem: cultura organizacional, integração, desenho de cargos e avaliação de desempenho", "consiste na integração, orientação para que o novo investidor conheça a empresa e o que se espera dele, onde ira investir e o acompanhamento do seu desempenho, incluem: cultura organizacional, integração, desenho de cargos e avaliação de desempenho", "consiste na integração, orientação para que a empresa busque uma melhora no seu desempenho e ganho.", "é definido como a situação onde o lider procura ajuda de negocio para a empresa ou para o setor comum");
const pg8 = new Questionario("O que é cultura organizacional?", "É o modo de pensar que predomina na organização e exprime a identidade organizacional que normalmente é baseada na cultura do dono", "É o modo de pensar que predomina na organização e exprime a identidade organizacional que normalmente é baseada na historia da cidade de onde vem a empresa", "É a cultura que envolve o produto como em comidas italianas de onde a cultura vem da italia", "É a integração de todas as culturas que envolvem o produto");
const pg9 = new Questionario("O Processos de Recompensar Pessoas é definido com:", "São processos utilizados para incentivar as pessoas e satisfazer suas necessidades individuais mais elevadas", "São processos utilizados para ganhar mais lucro usando o trabalho em dobro dos funcionarios", "São processos utilizados para criar ideias e inovação para a empresa", "São processos utilizados para pensar e criar ideias para a empresa");
const pg10 = new Questionario("No processo de recompensar pessoas temos dois tipos de recompensa que são classificadas como: ", "financeiras e não financeiras", "não financeiras e estrutural", "investimentos e financeiros", "presentes e não presentes");
const pg11 = new Questionario("O Processos de Desenvolver Pessoas é definido com:", "São os processos utilizados para capacitar e incrementar o desenvolvimento prossional e pessoal. Incluem treinamento, desenvolvimento, gestão do conhecimento e gestão de competências", "São processos utilizados para ganhar mais lucro usando o trabalho em dobro dos funcionarios", "São processos utilizados para pensar e criar ideias para a empresa", "São processos utilizados para incentivar as pessoas e satisfazer suas necessidades individuais mais elevadas");
const pg12 = new Questionario("O Processos de Manter Pessoas é definido com:", "São processos utilizados para criar condições ambientais e psicológicas satisfatórias para as atividades das pessoas", "São os processos utilizados para capacitar e incrementar o desenvolvimento prossional e pessoal. Incluem treinamento, desenvolvimento, gestão do conhecimento e gestão de competências", "São processos utilizados para ganhar mais lucro usando o trabalho em dobro dos funcionarios", "São processos utilizados para incentivar as pessoas e satisfazer suas necessidades individuais mais elevadas");
const pg13 = new Questionario("O Processos de Monitorar Pessoas é definido com:", "São processos de acompanhamento e controle das atividades das pessoas e vericação de resultados", "São processos utilizados para incentivar as pessoas e satisfazer suas necessidades individuais mais elevadas", "São os processos utilizados para capacitar e incrementar o desenvolvimento prossional", "São processos utilizados para ganhar mais lucro usando o trabalho em dobro dos funcionarios");
const pg14 = new Questionario("Todos os processos de gestão de pessoas são importantes?", "Sim, todos são igualmente importantes", "Não, temos uma ranking para classificar quais são os mais importantes", "Depende da empresa", "Fica a criterio do lider do setor");
const pg15 = new Questionario("Qual o significado da sigla DOM?", "Document Object Model", "Document Object Mescle", "Documents Obtruction Models", "Drag-and-Drop Object Model");
const pg16 = new Questionario("Tecnicas usando o DOM:", "tagname,id,name,classname,queryselector", "tagname,id,classname,queryselector", "tagname,id,name,classname,queryselector,input", "class,id,name,queryselector,body")
const pg17 = new Questionario("O que é CURVA DE INDIFERENÇA", "mostra as cestas que o consumidor considera indiferente, ou seja, as possíveis cestas que o consumidor desejaria adquirir", "mostra as cestas que o consumidor considera irelevante para compra, ou seja, os possiveis itens que ele ira adquirir", "mostra as curvas que o consumidor considera irelevante para compra, ou seja, os possiveis estudos que ele ira adquirir", "é a curva de negociação que o consumidor deseja adquirir a partir de um produto");
const pg18 = new Questionario("Em relação aos principais conceitos que servem de base para o estudo da economia, estão:", "Escolha, distribuição e necessidades.", "Capital, necessidades e produção.", "Escassez, ações e investimentos.", "Decisão, impostos e recursos.");
const pg19 = new Questionario("Economia é uma palavra grega e, se traduzida “ao pé da letra”, significa “administração da casa”, ou posteriormente, “administração da coisa pública”. Porém, ao definirmos economia, teremos outro conceito.", "É uma ciência social que procura alocar os recursos limitados, para satisfazer as necessidades da população", "É uma ciência social que estuda a relação entre imposto e PIB, e a melhor maneira de alocar os impostos", "É uma ciência social que procura distribuir bens e serviços entre a população mais carentes", "É uma ciência exata que procura maximizar a satisfação das necessidades ilimitadas das pessoas");

//const pg = new Questionario("", "", "", "", "");