const eco1 = new Questionario("O que é demanda:", "trata da procura do consumidor por um determinado bem ou serviço dados a renda e o preço do tempo", "trata da procura do consumidor por um determinado bem ou serviço dados a ideia e o preço do tempo", "trata da procura do empreendedor por um determinado bem ou serviço dados a renda e o preço do produto", "trata da compra do consumidor por um determinado estudo dados a renda e o preço do tempo do final");
const eco2 = new Questionario("Quais são os 3 termos importantes para definir a demanda?", "deseja, estar capacitado, tempo", "deseja, satisfação, tempo", "deseja, estar capacitado, compromisso", "poder de compra, estar capacitado, tempo");
const eco3 = new Questionario("O que é o EFEITO SUBSTITUIÇÃO:", " os consumidores vão substituir o consumo do bem por um outro bem, que chamamos de bem substituto", "os consumidores vão consumir o bem por um outro bem, que chamamos de bem substituto", "os consumidores vão substituir o consumo do bem por um tempo de trabalho para ganhar lucros, que chamamos de bem substituto", "o governo vai substituir o consumo do bem publico por um outro bem, que chamamos de bem obstruido");
const eco4 = new Questionario("O que é o EFEITO RENDA:", "Esse efeito nos diz que ao aumentar a renda, o consumidor demanda quantidades maiores de um determinado bem", "Esse efeito nos diz que ao aumentar a renda, o consumidor diminui a quantidade de um determinado bem", "Esse efeito nos diz que ao aumentar a renda, o consumidor prefere a compra de outro bem com o mesmo valor e qualidade", "Esse efeito nos diz que ao diminuir a renda, o consumidor demanda quantidades maiores de um determinado bem");
const eco5 = new Questionario("O que é alteração na quantidade demandada:", "quando não há um deslocamento da curva de demanda, mas apenas os pontos sobre a curva que deslocam", "quando há um deslocamento da curva de demanda, mas os pontos sobre a curva que deslocam", "quando não há um deslocamento da curva de demanda, porem os pontos sobre a curva que deslocam não são alterados", "quando não há um deslocamento da economia de setores, mas apenas as ideias sobre a curva que deslocam");
const eco6 = new Questionario("Quais são os fatores que afetam a curva de demanda?", "renda/propaganda/expectativa sobre o futuro/habitos", "renda/investimentos/expectativa sobre o futuro/habitos", "renda/propaganda/expectativa sobre o futuro/planejamento", "renda/crimes/expectativa sobre o futuro/habitos");
const eco7 = new Questionario("Quando falamos em uma alteração na quantidade demandada em função de uma variação no preço do próprio bem...", "a curva de demanda não se desloca, alterando apenas os pontos sobre a curva", "a curva de demanda se desloca, não alterando os pontos sobre a curva", "a curva de demanda não se desloca, alterando apenas as inicias da curva", "a curva de demanda se desloca, apenas fica com os pontos sobre a curva");

//const eco = new Questionario("", "", "", "", "");


