const ges1 = new Questionario("Conceito do treinamento de equipes é:", "uma prática cujo objetivo final é obter lucratividade ao permitir que as pessoas contribuam efetivamente para os resultados do negócio.", "uma prática cujo objetivo final acaba não gerando lucratividade ao permitir que as pessoas contribuam efetivamente para os resultados do negócio.", "uma prática cujo objetivo secundario é obter lucratividade ao permitir que as pessoas contribuam efetivamente para os resultados do negócio.", "uma prática cujo objetivo final não permitir que as pessoas contribuam efetivamente para os resultados do negócio e sim para si proprio.");
const ges2 = new Questionario("O treinamento de pessoas e equipes devem agregar:", "A todos", "Aos colaboradores", "As equipes", "Aos clientes");
const ges3 = new Questionario("O treinamento de pessoas e equipes deve atingir:", "resultados mensuráveis,principalmente na análise do custo-benefício do investimento", "Os resultados não são o foco do treinamento", "resultados mensuráveis,principalmente na análise do mercado de trabalho", "resultados mensuráveis,principalmente no setor onde o treinamento é realizado");
const ges4 = new Questionario("Quais são os tipos de treinamentos?", "Transmissão de informações, Desenvolvimento de habilidades específicas, Desenvolvimento de atitudes, Desenvolvimento de conceitos, Construção de competências", "Transmissão de informações, Desenvolvimento de habilidades pessoais, Desenvolvimento de atitudes, Desenvolvimento de conceitos, Construção de competências", "Transmissão de informações, Desenvolvimento de habilidades específicas, Desenvolvimento de atitudes, Desenvolvimento de ideias maiores, Construção de competências", "Transmissão de conceitos, Desenvolvimento de habilidades específicas, Desenvolvimento de atitudes, Desenvolvimento de conceitos, Construção de competências")
const ges5 = new Questionario(`<img class="mapa-mental" src="imagem/gestao_de_pessoas/ciclo do treinamento.png">`, "-", "-", "-", "-");
const ges6 = new Questionario("Quais são os processos de treinamento para um ciclo:", "Levantamento de necessidades, Programar o treinamento, Aplicar o treinamento, Avaliação de resultados", "Levantamento de necessidades, Programar a avaliação, Aplicar o desenvolvimento, Treinamento de resultados", "Levantamento de necessidades, Programar o treinamento, Aplicar o treinamento, Entrega dos certificados", "Levantamento de necessidades, Programar o treinamento, Aplicar os pensamentos, Avaliação de resultados");
const ges7 = new Questionario("Para desenvolver um programa de treinamento, o primeiro passo é..", "entender o que precisa ser resolvido e, a partir disso, o que se deve desenvolver nas pessoas que vão participar. Identificar o tipo de treinamento e pensar nas seguintes questões: por que fazer, para que, o que vai ser feito e como vai ser feito.", "entender o que precisa ser resolvido e, a partir disso, o que se deve desenvolver nas empresas que vão participar. Identificar o tipo de treinamento e pensar nas seguintes questões: por que fazer, para que, o que vai ser feito e como vai ser feito.", "entender o que precisa ser resolvido e, a partir disso, o que se deve desenvolver nas pessoas que vão participar. Identificar o tipo de treinamento e pensar nas seguintes questões: oque vai fazer, para que, o que não ser feito e como vai ser feito.", "entender o que precisa ser resolvido e, a partir disso, o que se deve desenvolver nas pessoas que vão participar. Identificar o tipo de forma e pensar nas seguintes questões: para onde ir, para que, o que vai ser feito e como vai ser feito.");
const ges8 = new Questionario(" tem o início, meio e fim e é normalmente planejado para resolver uma situação ou problema que existe para alcançar um novo resultado, ou seja, chegar a uma situação desejada. - A frase se refere a:", "Treinamento Convencional", "Educação Corporativa", "Universidade corporativa", "Treinamento de setor");
const ges9 = new Questionario("efere “a um sistema de aprendizagem contínua, que lhe permite ampliar seus conhecimentos, progredindo e fazendo carreira na empresa”. - A frase se refere a:", "Educação Corporativa", "Treinamento Convencional", "Universidade corporativa", "Treinamento de setor");
const ges10 = new Questionario("Conceito de Universidade Corporativa:", "As universidades corporativas visam formar e desenvolver os talentos humanos na gerência dos negócios, promovendo a gestão do conhecimento organizacional.", "As universidades corporativas visam formar e desenvolver os talentos humanos na gerência dos negócios, promovendo melhores cargo dentro da empresa.", "As universidades corporativas visam formar e desenvolver os talentos humanos na gerência dos negócios, promovendo maiores ganhos de investimento.", "As universidades corporativas visam formar e desenvolver os talentos corporativos na gerência dos negócios, promovendo a gestão do conhecimento pessoal.");
const ges11 = new Questionario("Alguns objetivos da educação corporativa:", "Trabalhar aptidões-chave para o seu negócio/Proporcionar um aprendizado voltado diretamente para a prática/Desenvolver competências de forma sistemática/Fixar os valores da organização/Contribuir para a identidade da organização por meio da fixação da cultura", "Trabalhar aptidões-chave para o seu negócio/Proporcionar um aprendizado voltado diretamente para a prática/Desenvolver competências de forma sistemática/Fixar os preço da organização/Contribuir para a identidade da organização por meio da fixação da cultura", "Trabalhar aptidões-chave para o seu negócio/Proporcionar um aprendizado voltado diretamente para a prática/Desenvolver competências de forma sistemática/Fixar os valores da organização/Contribuir para a identidade da organização por meio da fixação da educação", "Trabalhar aptidões-chave para o seu negócio/Proporcionar um aprendizado voltado diretamente para a teoria/Desenvolver competências de forma sistemática/Fixar os valores da organização/Contribuir para a identidade da organização por meio da fixação da cultura");
const ges12 = new Questionario("O modelo “Universidade Corporativa” deve ser considerado um processo educacional centrado especificamente nos negócios e não em um espaço físico destinado à aprendizagem. Visa treinar cadeia de valor e parceiros, inclusive clientes, distribuidores e fornecedores de produtos terceirizados, e como eles se relacionam com universidades que possam fornecer os futuros colaboradores da empresa. A afirmação esta:", "Correta", "Falsa", "Incompleta", "Quase correta");
const ges13 = new Questionario("Conceito de Equipe:", "Equipe se refere a um determinado número de pessoas com habilidades complementares que estão comprometidas com um propósito em comum, com metas de desempenho em comum e adotam uma abordagem pela qual se responsabilizam mutuamente.", "Equipe se refere a um determinado número de pessoas com habilidades complementares que estão comprometidas com um propósito em comum, com metas de desempenho em comum e adotam uma abordagem pela qual se responsabilizam pela sua parte.", "Equipe se refere a um determinado número de pessoas com habilidades complementares que estão comprometidas com um ideais opostos, com metas de desempenho em comum e adotam uma abordagem pela qual se responsabilizam mutuamente.", "Equipe se refere a um determinado número de pessoas com habilidades complementares que estão comprometidas com um ideais mutuo, com metas de desempenho em comum e adotam uma abordagem pela qual se responsabilizam mutuamente.");
const ges14 = new Questionario("Grupos e equipes:", "Tem significados diferentes", "Tem significados iguais", "De uma certa formas são identicos", "Uma parte do significado é diferente da outra e outra igual");
const ges15 = new Questionario("Grupo se refere:", "a duas ou mais pessoas que interagem, de modo que uma influencie a outra e vice-versa, e não necessariamente possuam objetivos comuns.", "a duas ou mais pessoas que interagem, de modo que uma influencie a outra e vice-versa, e possuam objetivos comuns.", "a duas ou mais pessoas que interagem, de modo que uma influencie a outra e vice-versa, e possuam objetivos comuns para um fim determinado.", "a duas ou mais pessoas que interagem, de modo que uma se afaste a outra e vice-versa, e possuam objetivos comuns para um fim determinado.");
const ges16 = new Questionario("Uma equipe é formada por:", "pessoas comprometidas com o todo, que tenham influência positiva, capacidade de utilizar habilidades complementares, cumprir metas e de prestar contas", "pessoas comprometidas com o todo, que tenham influência positiva, capacidade de utilizar habilidades complementares, cumprir metas e de uma certa forma não prestar contas", "pessoas comprometidas com o todo, que tenham influência positiva, capacidade de utilizar conceitos complementares, cumprir metas e de prestar contas", "pessoas comprometidas com o todo, que tenham influência negativas, capacidade de utilizar conceitos complementares, cumprir metas e de prestar contas");
const ges17 = new Questionario("Quando trabalhamos em equipe, quem ganha com isso:", "Todos ganham", "a organização", "os clientes", "gestores e investidores");
const ges18 = new Questionario("Pessoas que fazem partes de equipes normalmente possuem três tipos de habilidades:", "Habilidades técnicas/Habilidades para solucionar problemas/Habilidades nas relações interpessoais", "Habilidades pontuais/Habilidades para solucionar problemas/Habilidades nas relações interpessoais", "Habilidades técnicas/Habilidades para solucionar problemas/Habilidades nas relações pessoais", "Habilidades técnicas/Habilidades para criar problemas/Habilidades nas relações pessoais");
const ges19 = new Questionario("Ter um propósito único e metas de desempenho vão estabelecer:", "a harmonia e a direção da equipe, que vai se reunir e desenvolver todo o planejamento com foco nos objetivos estabelecidos.", "a harmonia e a direção da equipe, que vai se reunir e desenvolver todo o planejamento com foco nos acontecimentos frequentes.", "a harmonia e a direção da equipe, que vai se resumir e criar todo o planejamento com foco nos objetivos estabelecidos pelo cliente.", "a harmonia e a direção da equipe, que vai se reunir e desenvolver todo o planejamento com foco nos departamentos estabelecidos.");
const ges20 = new Questionario("Princípios da Andragogia significa", "é a denominação da “arte ou ciência de orientar adultos a aprender”, segundo a definição cunhada na década de 1970 por Malcolm Knowles.", "é a denominação da “arte ou ciência de orientar adultos a aprender”, segundo a definição cunhada na década de 1970 por Oliver Knowles.", "é a denominação da “arte ou pseudo-ciência de orientar adultos a aprender”, segundo a definição cunhada na década de 1970 por Malcolm Knowles.", "é a denominação da “noção ou ciência de orientar adultos a aprender”, segundo a definição cunhada na década de 1990 por Jackson Knowles.");
const ges21 = new Questionario("Princípios da Andragogia, princípios:", "1 Necessidade, 2 Autonomia, 3 Construir o aprendizado, 4 Ambiente Positivo", "1 Necessidade, 2 Construir o aprendizado, 3 Autonomia, 4 Ambiente Limpo", "1 Necessidade, 2 Construir o aprendizado, 3 Maquinas, 4 Ambiente Limpo", "1 Necessidade, 2 Construir o projeto, 3 Autonomia, 4 Ambiente Limpo");
const ges22 = new Questionario("Quando for aplicar um treinamento ou passar uma informação sobre uma mudança, pense por que essa nova ideia vai ser relevante para a equipe ou para quem vai receber a informação e como ela vai contribuir para a solução de problemas dos envolvidos. As pessoas decidem o que querem aprender e aplicar, por isso, desperte o interesse delas em querer receber e aplicar a nova informação ou treinamento.", "", "", "", "");

//const ges = new Questionario("", "", "", "", "");